In [34]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [32]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time =time.time()

elapsed_time = end_time -start_time
print(f"{elapsed_time:.8f}")

0.00099707
CPU times: total: 31.2 ms
Wall time: 997 µs


In [33]:
torch_rand1 =  torch.rand(100,100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")


0.189712
0.203649


In [16]:
probabilities = torch.tensor([0.5, 0.5])
samples =  torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([0, 0, 0, 1, 1, 0, 1, 0, 1, 0])


In [17]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [18]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [20]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))== 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [22]:
input = torch.zeros(2,3,4)
out =  input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [23]:
tensor1 = torch.tensor([1,2,3])
tensor2 =  torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([-3.4399,  1.7297,  4.3130], grad_fn=<SqueezeBackward4>)


In [28]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output =  F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [30]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])
embedded_output = embedding(input_indices)
print(embedded_output.shape)

torch.Size([4, 100])
