In [2]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [32]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time =time.time()

elapsed_time = end_time -start_time
print(f"{elapsed_time:.8f}")

0.00099707
CPU times: total: 31.2 ms
Wall time: 997 µs


In [33]:
torch_rand1 =  torch.rand(100,100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")


0.189712
0.203649


In [16]:
probabilities = torch.tensor([0.5, 0.5])
samples =  torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([0, 0, 0, 1, 1, 0, 1, 0, 1, 0])


In [17]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [18]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [20]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))== 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [22]:
input = torch.zeros(2,3,4)
out =  input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [23]:
tensor1 = torch.tensor([1,2,3])
tensor2 =  torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([-2.5286, -3.0113, -7.3609], grad_fn=<SqueezeBackward4>)


In [28]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output =  F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])
embedded_output = embedding(input_indices)
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 100])
tensor([[ 9.0854e-01,  1.5970e+00, -7.5493e-01, -3.8224e-01,  5.6940e-01,
          6.2343e-01, -3.1764e-01, -5.5774e-01, -1.0334e+00, -1.3519e-01,
          1.1269e+00, -1.1322e+00, -1.3812e+00, -4.9296e-01,  7.4850e-01,
          1.5189e+00, -2.5536e+00, -1.9269e+00,  2.8329e+00,  1.6680e-01,
          9.1528e-02,  6.4416e-01,  9.2887e-01,  6.3429e-01,  4.0757e-01,
          3.4026e-01,  1.2940e+00, -8.7769e-01,  1.7936e+00,  6.3468e-01,
         -3.6808e-01, -3.0655e-01, -1.5733e-01, -2.2280e+00,  4.3631e-02,
          1.0578e+00,  5.4438e-02, -2.2898e-01, -1.5659e-04, -8.8613e-01,
         -2.3975e-01,  1.0654e-01,  9.5561e-01,  1.5566e+00, -2.0395e-01,
          1.5430e+00,  4.6962e-01, -9.4870e-01, -6.9774e-01,  1.0003e+00,
         -1.7601e+00,  4.8459e-01, -7.4527e-02,  1.3909e+00, -7.2079e-01,
         -8.4460e-01, -1.6365e-02,  3.4888e-01,  9.3388e-01,  3.4376e-01,
         -3.3924e-01, -1.9186e+00,  5.3446e-01, -5.8778e-01, -1.0955e+00,
          5.4409e

In [8]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7,8,9], [10,11,12]])
print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [10]:
int_64 = torch.randint(1, (3,2)).float()
float_32 = torch.rand(2,3)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
